# Generated by Django 3.0.7 on 2020-06-16 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=13)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Equb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=13)),
                ('frequency', models.IntegerField()),
                ('received', models.ManyToManyField(to='moneypool.Client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='Equbs',
            field=models.ManyToManyField(to='moneypool.Equb'),
        ),
        migrations.AddField(
            model_name='client',
            name='friends',
            field=models.ManyToManyField(related_name='_client_friends_+', to='moneypool.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
