# Generated by Django 3.0.7 on 2020-06-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Equbs',
            field=models.ManyToManyField(blank=True, to='moneypool.Equb'),
        ),
        migrations.AlterField(
            model_name='client',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_client_friends_+', to='moneypool.Client'),
        ),
        migrations.AlterField(
            model_name='equb',
            name='received',
            field=models.ManyToManyField(blank=True, to='moneypool.Client'),
        ),
    ]
