# Generated by Django 3.0.7 on 2020-06-18 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0002_auto_20200616_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='money',
            new_name='bank_account',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Equbs',
            new_name='equbs',
        ),
        migrations.RenameField(
            model_name='equb',
            old_name='frequency',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='equb',
            name='cycle',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='equb',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equb',
            name='name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equb',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equb',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
        ),
    ]
