# Generated by Django 3.0.7 on 2020-06-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0003_auto_20200618_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
