# Generated by Django 3.0.7 on 2020-06-18 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0004_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
    ]
