# Generated by Django 3.0.7 on 2020-06-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0005_remove_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equb',
            name='received',
            field=models.ManyToManyField(blank=True, related_name='equb_received', to='moneypool.Client'),
        ),
    ]
