# Generated by Django 3.0.7 on 2020-06-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0006_auto_20200618_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='equbs',
            field=models.ManyToManyField(blank=True, related_name='clients', to='moneypool.Equb'),
        ),
    ]
