# Generated by Django 3.0.7 on 2020-06-19 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0008_auto_20200619_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancemanager',
            name='equb',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_manager', to='moneypool.Equb'),
        ),
    ]
