# Generated by Django 3.0.7 on 2020-06-20 23:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0012_auto_20200620_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='all_bids',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
