# Generated by Django 3.0.7 on 2020-06-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0013_auto_20200620_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancemanager',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
