# Generated by Django 3.0.7 on 2020-07-01 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0014_balancemanager_ended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit', to='moneypool.Client')),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equb', to='moneypool.Equb')),
            ],
        ),
    ]
