# Generated by Django 3.0.7 on 2020-07-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0015_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
