# Generated by Django 3.0.7 on 2020-07-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0016_auto_20200701_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='moneypool.Equb')),
                ('receiver', models.ManyToManyField(blank=True, related_name='received_invitations', to='moneypool.Client')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='moneypool.Client')),
            ],
        ),
    ]
