# Generated by Django 3.0.7 on 2020-07-06 20:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0017_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equb',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equb',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneypool.Client'),
        ),
        migrations.AddField(
            model_name='equb',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profit',
            name='equb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equb', to='moneypool.Equb'),
        ),
        migrations.CreateModel(
            name='SplitEqub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('relevant', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitequb', to='moneypool.Equb')),
                ('receivers', models.ManyToManyField(related_name='received_splitequbs', to='moneypool.Client')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_splitequb', to='moneypool.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('relevant', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_friendrequest', to='moneypool.Client')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendrequest', to='moneypool.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EqubRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('relevant', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equbrecommendation', to='moneypool.Equb')),
                ('receivers', models.ManyToManyField(related_name='received_equbrecommendations', to='moneypool.Client')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_equbrecommendation', to='moneypool.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveEqubInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('relevant', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activeequbinvite', to='moneypool.Equb')),
                ('receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_activeequbinvite', to='moneypool.Client')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_activeequbinvite', to='moneypool.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
