# Generated by Django 3.0.7 on 2020-07-07 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0018_auto_20200706_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqubInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('relevant', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equbinvites', to='moneypool.Equb')),
                ('receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_equbinvites', to='moneypool.Client')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_equbinvites', to='moneypool.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='equbrecommendation',
            name='equb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equbrecommendations', to='moneypool.Equb'),
        ),
        migrations.AlterField(
            model_name='equbrecommendation',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_equbrecommendations', to='moneypool.Client'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_friendrequests', to='moneypool.Client'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendrequests', to='moneypool.Client'),
        ),
        migrations.AlterField(
            model_name='splitequb',
            name='equb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitequbs', to='moneypool.Equb'),
        ),
        migrations.AlterField(
            model_name='splitequb',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_splitequbs', to='moneypool.Client'),
        ),
        migrations.DeleteModel(
            name='ActiveEqubInvite',
        ),
    ]
