# Generated by Django 3.0.7 on 2020-07-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0019_auto_20200707_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equb',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equbs', to='moneypool.Client'),
        ),
    ]
