# Generated by Django 3.0.7 on 2020-07-08 22:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0021_delete_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbids', to='moneypool.Equb')),
                ('receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_outbids', to='moneypool.Client')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_outbids', to='moneypool.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
