# Generated by Django 3.0.7 on 2020-07-10 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0022_outbid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount']},
        ),
        migrations.AlterModelOptions(
            name='equbinvite',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='equbrecommendation',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='outbid',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='splitequb',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='bid',
            name='all_bids',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='highest_bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='highest_bidder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='started',
        ),
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bid',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_bids', to='moneypool.Client'),
        ),
        migrations.AddField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bid',
            name='round',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='equb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='moneypool.Equb'),
        ),
        migrations.CreateModel(
            name='HighestBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneypool.Bid')),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highest_bids', to='moneypool.Equb')),
            ],
        ),
    ]
