# Generated by Django 3.0.7 on 2020-07-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0023_auto_20200710_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbid',
            name='receiver_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_outbids', to='moneypool.Bid'),
        ),
        migrations.AddField(
            model_name='outbid',
            name='sender_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_outbids', to='moneypool.Bid'),
        ),
    ]
