# Generated by Django 3.0.7 on 2020-07-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0024_auto_20200727_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbid',
            name='receiver_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_bids', to='moneypool.Bid'),
        ),
        migrations.AlterField(
            model_name='outbid',
            name='sender_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_bids', to='moneypool.Bid'),
        ),
    ]
