# Generated by Django 3.0.7 on 2020-11-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0026_auto_20200811_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-round', '-amount']},
        ),
    ]
